buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.10.0'
    }
}

repositories {
    google()
    mavenCentral()
}

apply plugin: 'com.android.application'

android {
    namespace "pl.czak.minimal"

    compileSdkVersion 35

    defaultConfig {
        targetSdk 35
    }
}
